### ISSUE TITLE
Python 2.5 support

### ISSUE THREAD

**Issue by valpackett** [zacharyvoase/urlobject#8]
urlobject doesn't work on 2.5…

```
File "/home/vagrant/virtualenv/python2.5/lib/python2.5/site-packages/urlobject/urlobject.py", line 110, in add_path_segment
    return self.with_path(self.path.add_segment(segment))
File "/home/vagrant/virtualenv/python2.5/lib/python2.5/site-packages/urlobject/urlobject.py", line 95, in with_path
    return self.__replace(path=path)
File "/home/vagrant/virtualenv/python2.5/lib/python2.5/site-packages/urlobject/urlobject.py", line 183, in __replace
    urlparse.urlsplit(self)._replace(**replace)))
AttributeError: 'SplitResult' object has no attribute '_replace'
```

Also, please host your docs on [Read The Docs](http://readthedocs.org/)!
